### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by issamjebnouni** [BeardedTek-com/RTSPScanner#2]
I got this error when i worked on a virtual environment to avoid conflicts and installed all necessary packages:
(test) C:\Users\jebno\Desktop\test>rtspscanner -m scan -c admin:Tunisys-2021 -a 172.21.40.10
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jebno\Desktop\test\Scripts\rtspscanner.exe\__main__.py", line 4, in <module>
  File "C:\Users\jebno\Desktop\test\lib\site-packages\rtspscanner.py", line 28, in <module>
    from portscan import PortScan
  File "C:\Users\jebno\Desktop\test\lib\site-packages\portscan.py", line 13, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

**Comment by T0biasCZe** [comment]
open portscan.py and remove `import resource `and `resource.setrlimit`
