### ISSUE TITLE
UnboundLocalError: local variable 'flaky' referenced before assignment

### ISSUE THREAD

**Issue by StefanoGiu** [BeardedTek-com/RTSPScanner#3]
UnboundLocalError: local variable 'flaky' referenced before assignment

rtspscanner -m scan

Running on Linux

**Comment by matt-pathr** [comment]
installed using `pip install rtspscanner` on to Ubuntu 20.04 LTS server
using `rtspscanner -m scan -a 192.168.130.110`  

i get the following error 
```
Traceback (most recent call last):
  File "/usr/local/bin/rtspscanner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/rtspscanner.py", line 274, in main
    scanner.scanner()
  File "/usr/local/lib/python3.8/dist-packages/rtspscanner.py", line 132, in scanner
    self.scanResults = {"cameras":self.cameras,"flaky":flaky,"portscan":results}
UnboundLocalError: local variable 'flaky' referenced before assignment
```

**Comment by ackl** [comment]
I am having the same issue

**Comment by dtrywets** [comment]
same issue here

**Comment by dave-vsdevs** [comment]
dito

**Comment by dave-vsdevs** [comment]
quick fix just move 

flaky = []

up to line 94 before the loop
